language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - master
    - dev

cache: yarn

script:
  - yarn
  - yarn lint
  - yarn build

notifications:
  slack: oHOeeFxLV+xfFncDhBD6dzo03YVld8KAXH08/vnYQrQaRPi3yi3gh9+YsP2o7xUp9vrrm8OGsAbAb2awFQvy7NOmEaF7zBS8QndPWtv3hs+JLvCZDYAkDRVFC5NYMr2ZCaHPPxLNRJuF+9jtOQqi3jnUQYSC0oOMfxsvJdGsRUuELGzz5wr3rNQ7AZOsZS8RHto4UEBX+g29S3lKosmsxerAjtsiTd1csTXEZQ1SDCp1GB/YVVQRAFw7kwfxG7WjS6ftCIdIyJI3Qb0o1qY08GAaIr7JyJ1ewIwfryVZjZtfrULlhuQ/OaVN0zZqFMIWE5lkMplJMpzJBxW4vEp/9vMSHDHkDF/e1B4+fJQ6U+DoFJVYny10kxOYfUtx88IHnldJAO3789NqyRntj9yvp7NK/HVXHGdxsmNFMpkxV6a+TDxfDAAtXBuxZT784LOAVzZm5hTIiF0vr9rZZEt198I3Hzmwx6MC444qrdDp/VqMCC7N1S+mAJyGQ+si/HYCjBdi6JHGr5VhF7Mk0d5Em2xLcpLK654QZTlsFl5fkK+ZIBxH2dNeoL1csiMW9be5+q0FImkwv35T97zswBlY8aBERfqD+DAe2pmgwsdkgqDqjdW+7jDByUhwvrTQ7ue+9gY07K0FecD3DbWUNzZPwy1NWrHRp15+vLbEalfiFuQ=

deploy:
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: broadway
    app: front-dev
    token: $OPENSHIFT_TOKEN
    on:
      branch: dev
    edge: true
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: broadway
    app: front-prod
    token: $OPENSHIFT_TOKEN
    on:
      branch: master
    edge: true
